name: CI

on:
  pull_request:
    branches: [main]

jobs:
  checks:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - run: pnpm install
      - name: Run ESLint
        run: pnpm exec biome lint .
      - name: Type-check
        run: pnpm exec turbo run typecheck
      - name: Run tests
        run: pnpm exec turbo run test
      - name: Build packages
        run: pnpm exec turbo run build 
      - name: Validate commit messages
        run: pnpm exec commitlint --from=HEAD~10